# Generated by Django 6.0 on 2026-01-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='context_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='model_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='answer',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='answer',
            name='retrieval_top_k',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
